classes:
- system.linux.system.single.debian
- system.openssh.server.team.cicd
parameters:
  _param:
    # TODO: Uncomment next line "linux_system_user_sudo: true" during the deployment.
    # Don't set it "false" before you configure sudo policies and enable power users.
    # linux_system_user_sudo: true
    docker_compose_image: apt:5000/compose:1.8.0
    apt_mk_version: "proposed"
#   apt_mk_version: "2018.8.0"
    aptly_server_hostname: apt
    aptly_server_address: 127.0.0.1
    linux_repo_refresh_db: true
    infra_config_hostname: apt01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # for docker-swarm
    cluster_node01_address: ${_param:aptly_server_address}
    admin_email: root@localhost
    # infra service addresses
    infra_config_address: ${_param:aptly_server_address}
    infra_config_deploy_address: ${_param:aptly_server_address}

    cluster_domain: mcp-offline.local
    cluster_name: mcp-offline

    control_network_netmask: 255.255.255.0
    tenant_network_netmask: 255.255.255.0

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    # Stub's
    deploy_network_netmask: 255.255.0.0
    deploy_network_gateway: 10.0.0.1

  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}
  linux:
    network:
      host:
        hostname:
          address: ${_param:single_address}
          names:
          - ${linux:network:hostname}
          - ${linux:network:fqdn}
        apt:
          address: ${_param:aptly_server_address}
          names:
          - ${_param:aptly_server_hostname}
          - ${_param:aptly_server_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      purge_repos: True
      service:
        apt-daily.timer:
          status: dead
          enabled: false
      user:
        root:
          password: false
      package:
        cloud-init:
          version: latest
        reclass:
          version: latest
